stages:
  - build
  - deploy

default:
  tags:
    - Low_Coding_Platform_Frontend

variables:
  ALIYUN: "registry.cn-hangzhou.aliyuncs.com/pipipan"

cache:
  paths:
    - node_modules/

build:
  image: node:16.13.2
  stage: build
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  image: docker:19.03.12
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - docker login --username=$ALIYUN_USERNAME --password=$ALIYUN_PASSWORD registry.cn-hangzhou.aliyuncs.com
    - docker build -t $ALIYUN/lcp-frontend:$CI_COMMIT_SHORT_SHA ./
    - docker push $ALIYUN/lcp-frontend:$CI_COMMIT_SHORT_SHA
